### ISSUE TITLE
Game Over Screen on Lose Condition

### ISSUE THREAD

**Issue by woodRock** [woodRock/front-of-house-frenzy#100]
## Goal
Go the Game Over screen upon the lose condition

## Task list: 
- [ ] Create Game Over widget
- [ ] Get Walkouts variable from MyInstance
- [ ] Create max walkouts variable
- [ ] Check for lose condition (walkouts > lose) 
- [ ] Open Game Over widget if lose condition

## Completion criteria: 
The Game Over widget is displayed on the screen when the lose condition is meet. I.e, the acceptable number of walkouts is exceeded.
