### ISSUE TITLE
Restore Main Level

### ISSUE THREAD

**Issue by woodRock** [woodRock/front-of-house-frenzy#112]
## Goal
Restore the `Main.umap` level to the game.

## Task list: 
- [ ] Revert previous commit 
- [ ] Cherry pick previous commit 
- [ ] Apply necessary changes 
- [ ] Keep `Main.umap`
- [ ] Merge changes with master

## Completion criteria: 
The Main level is back in the game, and functioning as intended.

**Comment by woodRock** [comment]
Success!

![main](https://user-images.githubusercontent.com/18411037/96081541-f8eddc80-0f15-11eb-8ded-8cd92822cf61.PNG)

**Comment by woodRock** [comment]
I have also tested the actual version of the game. Now the main menu level has been restored. And the game functions as intended.
