### ISSUE TITLE
Main Menu

### ISSUE THREAD

**Issue by woodRock** [woodRock/front-of-house-frenzy#20]
## Goal
A Main Menu user interface

## Tasks
- [x] Create Menu Widget 
- [x] Create Menu Level 
- [x] Play game, Options, Quit
- [x] Navigation to Game mode

## Success Criteria
The game starts with the main menu. From here the player can start a new game, adjust their options or quit.

**Comment by woodRock** [comment]
Used a placeholder image for the menu now. This will not be included in the release of the game. We are just waiting for a menu graphic to be made.

**Comment by woodRock** [comment]
This is a template menu with very limited functionality. It will be expanded upon and revised in later iterations of the design. It's low fidelity is more a proof of concept or coding spike.
