### ISSUE TITLE
Pause Menu

### ISSUE THREAD

**Issue by woodRock** [woodRock/front-of-house-frenzy#21]
## Goal
In game Pause menu.

## Tasks
- [x] Create Pause Widget 
- [x] Resume, Restart, Quit buttons
- [x] Add `ESC` key bind to pause the game
- [x] Resume, Restart, Quit functionality
- [x] Navigation to Main menu

## Success Criteria
During a game, a player can pause by hitting a key, e.g., `ESC`. From here they can resume or restart a level or quit to the main menu.
