### ISSUE TITLE
Main menu animated background

### ISSUE THREAD

**Issue by woodRock** [woodRock/front-of-house-frenzy#39]
## Goal
Have an animated background for the Main Menu that contains footage rendered using the in-game engine.
## Tasks
- [x] Add Level Props to Main Menu
- [x] Create Sequence 
- [x] Add Sequence to Main Menu 
- [x] Loop the sequence
- [x] Add the Main widget as an overlay

## Success Criteria
The game has an in-game rendered animated sequence for the background of the Main Menu. The loop is seamless and does not appear to contain any cuts.

**Comment by woodRock** [comment]
This was based on an unreal [tutorial](https://www.youtube.com/watch?v=jHGASFLaH1w) which is available online. The main menu uses a looping sequence-based of footage rendered using the in-game engine. The sequence can easily be edited as future improvements are made to the level design.

**Comment by woodRock** [comment]
Here is a quick demo [video](https://www.youtube.com/watch?v=VbUeLkYGE64) of the menu in action.

**Comment by woodRock** [comment]
![Capture](https://user-images.githubusercontent.com/18411037/92603699-ba0bac00-f303-11ea-92d1-92bdae1fb2a0.PNG)
