### ISSUE TITLE
Button hover animations

### ISSUE THREAD

**Issue by woodRock** [woodRock/front-of-house-frenzy#41]
## Goal
Style the main menu with animations, fonts, and overlays.

## Tasks
- [x] Import Menu font 
- [x] Make buttons transparent 
- [x] Change text font 
- [x] Hover animations

## Success Criteria
The main menu have an appropriate font, with hover animations, and no longer uses the default styling.

**Comment by woodRock** [comment]
A nice font for the menu and buttons that are under creative commons is available [here](https://www.fontpalace.com/font-download/artisan-12/)

**Comment by woodRock** [comment]
This is a continuation of #39 and the based off of this [tutorial](https://www.youtube.com/watch?v=jHGASFLaH1w).

**Comment by woodRock** [comment]
Here is a [demo](https://www.youtube.com/watch?v=hwBJA80ya9Y) of the current version.
