### ISSUE TITLE
Basic Customer NPC

### ISSUE THREAD

**Issue by woodRock** [woodRock/front-of-house-frenzy#5]
## Goal
Create a basic blueprint for the customer NPC 

## Tasks
- [x] Create customer NPC blueprint
- [x] Add temporary mesh
- [x] Add customers' patience variable (seconds)
- [x] Player interaction resets patience

## Success Criteria
Customer NPC can arrive at the door. Their patience begins to deteriorate. Player interaction resets patience.
