### ISSUE TITLE
Menu blur and text fade 

### ISSUE THREAD

**Issue by woodRock** [woodRock/front-of-house-frenzy#50]
## Goal
Make the text on each of the menus fade in and out.

## Tasks
- [x] Create Fade animation
- [x] Fade in when entering a menu 
- [x] Fade out when leaving a menu
- [x] Add some blur to the background

## Success Criteria
The menus have animations when the player enters and exits them. This makes them more seamless. Also, the Main Menu could to with a background blur around its edges.

**Comment by woodRock** [comment]
Two animations were created. Each is played when the menu initially opens. Then they are played in reverse when the player exits theme menus.
