### ISSUE TITLE
Fix pause menu

### ISSUE THREAD

**Issue by woodRock** [woodRock/front-of-house-frenzy#51]
## Goal
The pause menu functionality was removed by another merge request. This needs to be added back to the game.

## Tasks
- [x] Create Event on "M" keypress
- [x] Add Pause Menu Widget to screen
- [x] Set player cursor to show

## Success Criteria
The player can pause the game when they push the "M" key. And their mouse cursor will appear for navigation.

**Comment by woodRock** [comment]
The pause menu simply had to be added to the level blueprint for `Level1`. It is triggered upon the event of an "M" keypress.
