### ISSUE TITLE
Patience Widget

### ISSUE THREAD

**Issue by woodRock** [woodRock/front-of-house-frenzy#57]
## Goal
A widget is displayed by the customer once they have run out of patience.

## Task list: 
- [ ] Create patience alert widget 
- [ ] Display by customer if they have no patience 
- [ ] Remove widget when the patience is reset

## Completion criteria: 
A patience widget will be displayed by a customer once there patience has depleted. When the server interacts with the customer the widget will disappear.

**Comment by woodRock** [comment]
![danger](https://user-images.githubusercontent.com/18411037/93293998-7e11a300-f83d-11ea-99f1-fb82da5d3503.PNG)
