### ISSUE TITLE
Background music

### ISSUE THREAD

**Issue by woodRock** [woodRock/front-of-house-frenzy#61]
## Goal
Background music is needed for the main menu

## Task list: 
- [x] Placeholder royalty free music 
- [x] Convert to .wav
- [x] Add to main menu
- [ ] (Optional) compose original theme music

## Completion criteria: 
The main menu has background music playing.

**Comment by woodRock** [comment]
Used [Comedy History](https://www.royaltyfree-music.com/free-music-download) as a placeholder for the main menu music.
