### ISSUE TITLE
Seat a customer

### ISSUE THREAD

**Issue by Raine1998** [woodRock/front-of-house-frenzy#65]
## Goal
Customers can be seated by mouse click

## Task list: 
- [x] Mouse cursor appears on screen during game

- [x] Cursor recognises customer and table

- [x] Upon click of both, customer is moved to table location

## Completion criteria: 
When tasks are completed. Also animations added (if any)

**Comment by Raine1998** [comment]
Simple point and click movement; Need to redo to be part of a behaviour tree
