### ISSUE TITLE
Make patience bar using  widgets for NPCs

### ISSUE THREAD

**Issue by woodRock** [woodRock/front-of-house-frenzy#72]
## Goal
A patience bar is used to indicate each customer current patience.

## Task list: 
What is needed to complete this issue? 
- [ ] Create patient widget(s) 
- [ ] happy, moderate, warning, angry (emojis?)
- [ ] Display widgets on screen relative to world location of customer

## Completion criteria: 
We have a clear indication of the current progress of each customer. With alerts at important stages. It should be clear to a player when a customer is about to walk out. And when they are not far from requiring attention.
