### ISSUE TITLE
Behaviour Tree for Customer NPC

### ISSUE THREAD

**Issue by Raine1998** [woodRock/front-of-house-frenzy#76]
## Goal
Full AI Behaviour for Customer should work 

## Task list: 
Complete all logic for tasks in the behaviour tree:

- [ ] WaitAtDoor

- [ ] LeaveAngry

- [ ] LootAtMenu

- [ ] OrderFood

- [ ]  WaitForFood

- [ ] EatFood

- [ ] LeaveHappy

## Completion criteria: 
When each scenario can be reached: 
- [ ] Leave at door

- [ ] Leave while waiting to order

- [ ] Leave while waiting for food

- [ ] Pay and leave after eating fully
