### ISSUE TITLE
Soundtrack

### ISSUE THREAD

**Issue by woodRock** [woodRock/front-of-house-frenzy#82]
## Goal
Compose the game sound track.

## Task list: 
- [ ] Main Theme - Menu Music
- [ ] Game Music
- [ ] Import as `.WAV`
- [ ] Add to game

## Completion criteria: 
Compose the game's sound track. This consists of two themes. A main theme, and gameplay soundtrack.
