### ISSUE TITLE
Display bubble with order when within distance of table (Deteriorate patience)

### ISSUE THREAD

**Issue by toemily** [woodRock/front-of-house-frenzy#91]
## Goal
Display an order bubble with the customer's order once a customer has been seated.

## Task list: 
- [x] Check box collision for customer and player 
- [x] (Testing) print string for their food order
- [ ] Create an order bubble widget 
- [ ] Translate customer world position to screen position
- [ ] Display food icon in the widget

## Completion criteria: 
Once a customer has been seated. We display an order bubble with their desired food above there head, when the waiter is close enough to take the order.
